import { Link } from "react-router-dom";
import { FooterBar } from "@/components/FooterBar.tsx";
import { HeaderBar } from "@/components/HeaderBar.tsx";
import { useTheme } from "@/hooks/useTheme.ts";

function BackLink() {
	return (
		<Link
			to="/"
			className="mb-8 inline-flex items-center gap-1.5 text-sm text-[var(--color-accent)] transition hover:opacity-75"
		>
			<svg
				aria-hidden="true"
				viewBox="0 0 24 24"
				className="h-4 w-4"
				fill="none"
				stroke="currentColor"
				strokeWidth="2"
			>
				<path d="M19 12H5M12 5l-7 7 7 7" />
			</svg>
			Back to app
		</Link>
	);
}

function SectionHeading({ number, title }: { number: number; title: string }) {
	return (
		<h2 className="mb-3 mt-10 flex items-baseline gap-2 text-lg font-semibold text-[var(--color-text)]">
			<span className="font-bold text-[var(--color-accent)]">{number}.</span>
			{title}
		</h2>
	);
}

export function TermsPage() {
	const { theme, toggleTheme } = useTheme();

	return (
		<main className="flex h-screen flex-col overflow-hidden bg-[var(--color-primary)] text-[var(--color-text)]">
			<HeaderBar theme={theme} onThemeToggle={toggleTheme} />

			<div className="flex-1 overflow-y-auto">
				<article className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
					<BackLink />

					<h1 className="text-2xl font-bold text-[var(--color-text)] sm:text-3xl">
						Terms of Service
					</h1>
					<p className="mt-1 text-sm text-[var(--color-text)]/60">
						Last updated: June 2026
					</p>

					<hr className="my-6 border-[var(--color-tertiary)]" />

					<SectionHeading number={1} title="Acceptance" />
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						By using AskDocuMind ("the Service"), you agree to these Terms of Service.
						If you do not agree, do not use the Service.
					</p>

					<SectionHeading number={2} title="What the Service does" />
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						AskDocuMind allows you to upload documents and ask questions about their
						content using AI. It is provided as-is, primarily as a portfolio
						demonstration project.
					</p>

					<SectionHeading number={3} title="Acceptable use" />
					<p className="mb-3 text-sm leading-relaxed text-[var(--color-text)]/80">
						You may use AskDocuMind for lawful, personal, or educational purposes. You
						agree{" "}
						<strong className="font-semibold text-[var(--color-text)]">not</strong> to:
					</p>
					<ul className="space-y-2 text-sm leading-relaxed text-[var(--color-text)]/80">
						{[
							"Upload documents containing illegal content, including material that infringes copyright, contains child sexual abuse material, or constitutes unlawful threats or harassment",
							"Upload documents containing sensitive personal data of others (medical records, financial records, credentials) without their consent",
							"Attempt to extract, reverse-engineer, or abuse the underlying AI prompts or system instructions",
							"Use the Service to generate content intended to deceive, defraud, or harm others",
							"Send automated or scripted requests in a manner that circumvents rate limits or disrupts the Service for other users",
							"Upload files containing malware, exploits, or other malicious content",
						].map((item) => (
							<li key={item} className="flex gap-2">
								<span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-accent)]" />
								<span>{item}</span>
							</li>
						))}
					</ul>

					<SectionHeading number={4} title="Uploaded content" />
					<p className="mb-3 text-sm leading-relaxed text-[var(--color-text)]/80">
						You retain ownership of any documents you upload. By uploading, you grant
						AskDocuMind a temporary licence to process and store the content solely for
						the purpose of answering your queries. This licence ends when your session
						expires and your data is deleted.
					</p>
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						You are solely responsible for ensuring you have the right to upload and
						process any documents you submit.
					</p>

					<SectionHeading number={5} title="AI-generated responses" />
					<p className="mb-3 text-sm leading-relaxed text-[var(--color-text)]/80">
						Responses are generated by a large language model (OpenAI GPT). They are
						based on the content of your uploaded documents and, optionally, web search
						results. You acknowledge that:
					</p>
					<ul className="space-y-2 text-sm leading-relaxed text-[var(--color-text)]/80">
						{[
							"AI responses may be incomplete, incorrect, or misleading",
							"Responses must not be relied upon for medical, legal, financial, or safety-critical decisions",
							"The Service makes no guarantee of accuracy, completeness, or fitness for any particular purpose",
						].map((item) => (
							<li key={item} className="flex gap-2">
								<span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-accent)]" />
								<span>{item}</span>
							</li>
						))}
					</ul>

					<SectionHeading number={6} title="Service availability and limitations" />
					<ul className="space-y-2 text-sm leading-relaxed text-[var(--color-text)]/80">
						{[
							"The Service is provided on a best-effort basis with no uptime guarantees",
							"Sessions are limited in duration (1 hour) and document upload capacity (2 MB total per session, 10 documents maximum)",
							"Web search functionality (if enabled) is subject to third-party availability and monthly quota limits",
							"We reserve the right to suspend or terminate access at any time, without notice, for violations of these Terms or for operational reasons",
						].map((item) => (
							<li key={item} className="flex gap-2">
								<span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-accent)]" />
								<span>{item}</span>
							</li>
						))}
					</ul>

					<SectionHeading number={7} title="Limitation of liability" />
					<p className="mb-3 text-sm leading-relaxed text-[var(--color-text)]/80">
						To the fullest extent permitted by law:
					</p>
					<ul className="space-y-2 text-sm leading-relaxed text-[var(--color-text)]/80">
						{[
							'AskDocuMind is provided "as is" without warranties of any kind, express or implied',
							"We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to loss of data, loss of business, or harm resulting from reliance on AI-generated responses",
							"Our total liability to you for any claim arising from use of the Service shall not exceed £0, as the Service is provided free of charge",
						].map((item) => (
							<li key={item} className="flex gap-2">
								<span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-accent)]" />
								<span>{item}</span>
							</li>
						))}
					</ul>

					<SectionHeading number={8} title="Changes to the Service and Terms" />
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						We may update these Terms at any time. Continued use of the Service after
						changes are posted constitutes acceptance of the updated Terms.
					</p>

					<SectionHeading number={9} title="Governing law" />
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						These Terms are governed by the laws of England and Wales.
					</p>

					<SectionHeading number={10} title="Contact" />
					<p className="text-sm leading-relaxed text-[var(--color-text)]/80">
						For queries about these Terms:{" "}
						<a
							href="mailto:madukaagbeze.ea@gmail.com"
							className="text-[var(--color-accent)] underline-offset-2 hover:underline"
						>
							madukaagbeze.ea@gmail.com
						</a>
					</p>

					<div className="mt-12 pb-4">
						<BackLink />
					</div>
				</article>
			</div>

			<FooterBar />
		</main>
	);
}
